name: FuzzingScan
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    services:
      docker:
        image: docker
        options: --privileged
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
 
      - name: Build Docker image for web app_fuzzing
        run: docker build -t web-app .
 
      - name: Create Docker network
        run: docker network create webapp-network
 
      - name: Stop and remove previous container
        run: |
          docker stop web-app || true
          docker rm web-app || true
 
      - name: Run web app_fuzzing
        run: docker run -d --name web-app --network webapp-network web-app
 
      - name: Run FFUF fuzzing for app
        run: docker exec web-app /bin/sh -c "
          ./ffuf/ffuf -w /app_fuzzing/wordlist.txt -u http://web-app:5001 -o /app_fuzzing/ffuf_results.json && \
          ls -l /app_fuzzing && cat /app_fuzzing/ffuf_results.json || echo 'No results found'" 
 
      - name: Upload FFUF results
        uses: actions/upload-artifact@v4
        with:
          name: ffuf-results
          path: /app_fuzzing/ffuf_results.json